name: 同步到Gitee

on:
  workflow_dispatch:
    inputs:
      FORCE_MIRROR:
        description: '开启强制同步至Gitee'
        required: false
        default: false
        type: boolean

env:
  DESTINATION_HOSTNAME: gitee.com
  GITEE_USER_NAME: shuaige668
  GITHUB_USER_NAME: shidahuilang

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || !github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - githubRepoName: shuyuan
            giteeRepoName: shuyuan
          - githubRepoName: QL-
            giteeRepoName: qinglong
          - githubRepoName: pve
            giteeRepoName: pve
          - githubRepoName: QuantumultX
            giteeRepoName: QuantumultX
          - githubRepoName: common
            giteeRepoName: common
          - githubRepoName: SS-SSR-TG-iptables-bt
            giteeRepoName: SS-SSR-TG-iptables-bt           
          - githubRepoName: btpanel
            giteeRepoName: btpanel
          - githubRepoName: openwrt
            giteeRepoName: openwrt
          #- githubRepoName: facefusion
          #  giteeRepoName: facefusion
            
    steps:
      - name: 获取提交哈希
        id: getHash
        run: |
          githubRepoDir=$GITHUB_USER_NAME-${{ matrix.githubRepoName }}
          echo "githubRepoDir=$githubRepoDir" >> $GITHUB_ENV
          git clone --depth 1 https://github.com/$GITHUB_USER_NAME/${{ matrix.githubRepoName }} $githubRepoDir
          cd $githubRepoDir
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          rm -rf $githubRepoDir

      - name: 比较提交哈希
        id: compareHash
        uses: actions/cache@v4
        with:
          path: .commitHash
          key: ${{ env.GITHUB_USER_NAME }}-${{ steps.getHash.outputs.commitHash }}

      - name: 生成提交哈希
        if: steps.compareHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: GitHub同步到Gitee
        continue-on-error: true
        if: steps.compareHash.outputs.cache-hit != 'true' || github.event.inputs.FORCE_MIRROR == 'true'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:${{ env.GITHUB_USER_NAME }}/${{ matrix.githubRepoName }}.git"
          destination-repo: "git@${{ env.DESTINATION_HOSTNAME }}:${{ env.GITEE_USER_NAME }}/${{ matrix.giteeRepoName }}.git"
         # options: "-o StrictHostKeyChecking=yes"

      - name: 删除旧的工作流运行
        uses: JuvenileQ/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
